spring:
  datasource:
    #    url: jdbc:mysql://mysql-docker:3306/xcx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=CST
    #    username: root
    #    password: 11111111
    url: jdbc:mysql://localhost:3306/xcx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=CST
    username: root
    password: 11111111
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      #      ddl-auto: update
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
#        naming.physical-strategy: org.hibernate.cfg.EJB3NamingStrategy
#        naming.implicit-strategy: org.hibernate.cfg.EJB3NamingStrategy
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
server:
  port: 8888
