spring:
  datasource:
#    url: jdbc:mysql://host.docker.internal:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=CST
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=CST
    username: root
    password: 11111111
  jpa:
    database: mysql
    show-sql: true
    hibernate:
#      ddl-auto: update
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      jdbc:
        batch_size: 10
        order_inserts: true
      hibernate:
        format_sql: true
#        naming.physical-strategy: org.hibernate.cfg.EJB3NamingStrategy
#        naming.implicit-strategy: org.hibernate.cfg.EJB3NamingStrategy
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
server:
  port: 8888
